#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SIGEMDB")]
	public partial class SIGEMDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSupplySpaceShip(SupplySpaceShip instance);
    partial void UpdateSupplySpaceShip(SupplySpaceShip instance);
    partial void DeleteSupplySpaceShip(SupplySpaceShip instance);
    #endregion
		
		public SIGEMDBDataContext() : 
				base(global::SIGEM.Data.Properties.Settings.Default.SIGEMDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SIGEMDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SIGEMDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SIGEMDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SIGEMDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SupplySpaceShip> SupplySpaceShips
		{
			get
			{
				return this.GetTable<SupplySpaceShip>();
			}
		}
		
		public System.Data.Linq.Table<SpaceShip> SpaceShips
		{
			get
			{
				return this.GetTable<SpaceShip>();
			}
		}
	}
	
	[Table(Name="dbo.SupplySpaceShip")]
	public partial class SupplySpaceShip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public SupplySpaceShip()
		{
			OnCreated();
		}
		
		[Column(Storage="_Id", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.SpaceShip")]
	public partial class SpaceShip
	{
		
		private string _Id;
		
		private string _Name;
		
		private int _MaximumPassengers;
		
		private string _SupplySpaceShipOrigin;
		
		private string _SupplySpaceShipDestination;
		
		public SpaceShip()
		{
		}
		
		[Column(Storage="_Id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_MaximumPassengers", DbType="Int NOT NULL")]
		public int MaximumPassengers
		{
			get
			{
				return this._MaximumPassengers;
			}
			set
			{
				if ((this._MaximumPassengers != value))
				{
					this._MaximumPassengers = value;
				}
			}
		}
		
		[Column(Storage="_SupplySpaceShipOrigin", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SupplySpaceShipOrigin
		{
			get
			{
				return this._SupplySpaceShipOrigin;
			}
			set
			{
				if ((this._SupplySpaceShipOrigin != value))
				{
					this._SupplySpaceShipOrigin = value;
				}
			}
		}
		
		[Column(Storage="_SupplySpaceShipDestination", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SupplySpaceShipDestination
		{
			get
			{
				return this._SupplySpaceShipDestination;
			}
			set
			{
				if ((this._SupplySpaceShipDestination != value))
				{
					this._SupplySpaceShipDestination = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
