<?xml version="1.0" encoding="utf-8"?>
<Database Name="SIGEMDB" Class="SIGEMDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\SIGEMDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="SIGEM.Data.Properties.Settings" SettingsPropertyName="SIGEMDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SupplySpaceShip" Member="SupplySpaceShips">
    <Type Name="SupplySpaceShip">
      <Column Name="Id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SpaceShip" Member="SpaceShips">
    <Type Name="SpaceShip">
      <Column Name="Id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaximumPassengers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplySpaceShipOrigin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SupplySpaceShipDestination" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Passenger" Member="Passengers">
    <Type Name="Passenger">
      <Column Name="Id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Passenger_SpaceShipOcupation" Member="SpaceShipOcupations" OtherKey="Id_Passenger" Type="SpaceShipOcupation" />
    </Type>
  </Table>
  <Table Name="dbo.SpaceShipOcupation" Member="SpaceShipOcupations">
    <Type Name="SpaceShipOcupation">
      <Column Name="Id_Passenger" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_SpaceShip" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Passenger_SpaceShipOcupation" Member="Passenger" ThisKey="Id_Passenger" Type="Passenger" IsForeignKey="true" />
    </Type>
  </Table>
</Database>